### ISSUE TITLE
6.4 制限を超えたとき のリミット設定値が少ないと設定した時点でエラーになる

### ISSUE THREAD

**Issue by niku** [tatsu-zine/naruhounix#64]
読んでいる本のバージョンは v1.1.2 です．

```ruby
/Users/niku% irb
irb(main):001:0> RUBY_VERSION
=> "2.3.0"
irb(main):002:0> Process.setrlimit(:NOFILE, 3)
=> nil
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/input-method.rb:149:in `input=': Invalid argument - dup (Errno::EINVAL)
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/input-method.rb:149:in `gets'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:469:in `block (2 levels) in eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:623:in `signal_status'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:468:in `block in eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:189:in `buf_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:104:in `getc'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/slex.rb:206:in `match_io'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/slex.rb:76:in `match'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:283:in `token'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:265:in `lex'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:485:in `eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:395:in `block in start'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:394:in `catch'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:394:in `start'
        from /usr/local/var/rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

手元の Ruby2.3.0 だと 8 までは同じようなエラーになり，9 だと想定した動作になるようです．

irb が動作するための最低限のファイルリミット数が変わって(8つ？)いるので，
9 未満に設定した時点で動けなくなりエラーになるのかなと推測しました．

```ruby
/Users/niku% irb
irb(main):001:0> null = File.open("/dev/null")
=> #<File:/dev/null>
irb(main):002:0> null.fileno
=> 9
irb(main):003:0> null.close
=> nil
irb(main):004:0> Process.setrlimit(:NOFILE, 9)
=> nil
irb(main):005:0> Process.setrlimit(:NOFILE, 8)
=> nil
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/input-method.rb:150:in `output=': Too many open files - dup (Errno::EMFILE)
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/input-method.rb:150:in `gets'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:469:in `block (2 levels) in eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:623:in `signal_status'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:468:in `block in eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:189:in `buf_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:104:in `getc'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/slex.rb:206:in `match_io'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/slex.rb:76:in `match'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:283:in `token'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:265:in `lex'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:485:in `eval_input'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:395:in `block in start'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:394:in `catch'
        from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/irb.rb:394:in `start'
        from /usr/local/var/rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

初学者が本に書いてある内容を打ち込んでいきなりスタックトレースが表示されると
問題の切り分けができるまでは戸惑いそうです．

**Comment by snoozer05** [comment]
@niku こちらやっと方針を決めまして、訳注にて補足する形で対応することにしました。遅くなってしまいましたが、報告助かりました！ありがとうございます 🙏
